import b1 from '../../assets/b1.jpg';
import b2 from '../../assets/b2.jpg';
import b3 from '../../assets/b3.jpg';

export const demoProduct = [
  {
    id: 1,
    name: 'product1',
    price: 99,
    image: b1,
    stck: 'Available',
    cat: 'Meat-&-Fish',
  },
  {
    id: 2,
    name: 'product2',
    price: 89,
    image: b2,
    stck: 'Available',
    cat: 'vegetables',
  },
  {
    id: 3,
    name: 'product3',
    price: 999,
    image: b3,
    stck: 'Available',
    cat: 'Dried-Goods',
  },
  {
    id: 4,
    name: 'product4',
    price: 99,
    image: b1,
    stck: 'Available',
    cat: 'vegitable',
  },
  {
    id: 5,
    name: 'product5',
    price: 99,
    image: b2,
    stck: 'Available',
    cat: 'Meat-&-Fish',
  },
  {
    id: 6,
    name: 'product6',
    price: 99,
    image: b3,
    stck: 'Available',
    cat: 'Dried-Goods',
  },
  {
    id: 7,
    name: 'product7',
    price: 99,
    image: b1,
    stck: 'Available',
    cat: 'Meat-&-Fish',
  },
  {
    id: 8,
    name: 'product8',
    price: 99,
    image: b2,
    stck: 'Available',
    cat: 'Dried-Goods',
  },
  {
    id: 9,
    name: 'product8',
    price: 99,
    image: b2,
    stck: 'Available',
    cat: 'Meat-&-Fish',
  },
  {
    id: 10,
    name: 'product8',
    price: 99,
    image: b2,
    stck: 'Available',
    cat: 'vegitable',
  },
  {
    id: 11,
    name: 'product8',
    price: 99,
    image: b2,
    stck: 'Available',
    cat: 'Meat&Fish',
  },
];
